dwindle {
	preserve_split = true
}

master {
	new_status = master
}

input {
	kb_layout = us, ru
	kb_options = grp:caps_toggle

	follow_mouse = 1

	accel_profile=flat 
	sensitivity = 0
}

render {
	direct_scanout = 0
}

