$mainMod = SUPER

# clipboard manager
bindr = ALT, V, exec, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy

# emoji picker
bindr = $mainMod, E, exec, rofi -modi emoji -show emoji

# terminal emulator
bind = $mainMod, Return, exec, kitty

# app launcher
bind = $mainMod, Super_L, exec, pkill rofi || rofi -show drun
bind = $mainMod, R, exec, pkill rofi || rofi -show run

# lock session
bind = $mainMod SHIFT, L, exec, hyprlock

# screenshot
bind = , Print, exec, ~/.config/scripts/screenshots/screenshot.sh selection
bind = SHIFT, Print, exec, ~/.config/scripts/screenshots/screenshot.sh output
bind = CTRL, Print, exec, ~/.config/scripts/screenshots/screenshot.sh activewindow

# volume
bindel = ,XF86AudioRaiseVolume, exec, ~/.config/scripts/volume-control/volume.sh increase
bindel = ,XF86AudioLowerVolume, exec, ~/.config/scripts/volume-control/volume.sh decrease
bindel = ,XF86AudioMute, exec, ~/.config/scripts/volume-control/volume.sh mute

# player
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous


# window manager
# # # # # # # # # 

# active window actions
bind = $mainMod, C, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, S, layoutmsg, togglesplit # dwindle
bind = $mainMod SHIFT, F, fullscreenstate, 2 # fake fullscreen
bind = $mainMod, F, fullscreenstate, 0 2 # fake fullscreen

# Move focus with mainMod + HJKL
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Move windows with mainMod + ctrl + HJKL
bind = $mainMod CTRL, H, swapwindow, l
bind = $mainMod CTRL, J, swapwindow, d
bind = $mainMod CTRL, K, swapwindow, u
bind = $mainMod CTRL, L, swapwindow, r

# Resize windows with mainMod + shift + HJKL
binde = $mainMod ALT, H, resizeactive, -50 0
binde = $mainMod ALT, J, resizeactive, 0 50
binde = $mainMod ALT, K, resizeactive, 0 -50
binde = $mainMod ALT, L, resizeactive, 50 0

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Cycle workspaces with arrows
bind = $mainMod, Left, workspace, m-1
bind = $mainMod, Right, workspace, m+1

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
# bind = $mainMod, S, togglespecialworkspace, magic
# bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = SHIFT, F8, exec, echo "toggle_record" | nc -U -u -w0 /tmp/macro_bot.sock
bind = SHIFT, F9, exec, echo "toggle_play"   | nc -U -u -w0 /tmp/macro_bot.sock
bind = SHIFT, Escape, exec, echo "exit"      | nc -U -u -w0 /tmp/macro_bot.sock

# PASSED KEYBINDS
bind = , F9, pass, class:^(com\.obsproject\.Studio)$
