general {
	gaps_in = 3
	gaps_out = 6

	border_size = 3

	col.active_border = rgba(000000ff)
	col.inactive_border = rgba(000000ff)

	layout = dwindle

	allow_tearing = true
}

decoration {
	rounding = 12
	rounding_power = 0

	active_opacity = 1.0
	inactive_opacity = 1.0

	shadow {
		enabled = true
		range = 5
		render_power = 3
		color = rgba(0000000f)
	}

	blur {
		enabled = false
		size = 3
		passes = 1

		vibrancy = 0.1696
	}
}
