windowrule = match:class xdg-desktop-portal-gtk, float 1, center 1
windowrule = match:class mpv, float 1, center 1
windowrule = match:class feh, float 1, center 1
windowrule = match:class mpv-audio, float 1, center 1, size 360 80
windowrule = match:class ^(steam_app_*)$, immediate 1
