preset=3
position=top_right
font_size=12

cpu_stats=1
cpu_temp=1
cpu_power=1
cpu_mhz=1
core_load=1

gpu_stats=1
gpu_temp=1
gpu_junction_temp=1
gpu_mem_temp=1
gpu_core_clock=1
gpu_mem_clock=1
gpu_power=1
gpu_voltage=1

ram=1
vram=1

autostart_log=0
log_interval=100
output_folder=/home/tonbix/mangohud_logs
