source = ./hyprland.d/animations.conf
source = ./hyprland.d/autorun.conf
source = ./hyprland.d/behavior.conf
source = ./hyprland.d/binds.conf
source = ./hyprland.d/env.conf
source = ./hyprland.d/monitors.conf
source = ./hyprland.d/styling.conf
source = ./hyprland.d/windowrules.conf
