[mgr]
border_symbol = " "

[icon]
globs = []
dirs = []
files = []
exts = []
conds = []

[indicator]
padding = { open = " ", close = " " }

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
